//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4AppFuncional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodegas
    {
        public int IdCategoria { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Responsable { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string CveProvedor { get; set; }
        public Nullable<decimal> PrecioMenor { get; set; }
        public Nullable<decimal> PrecioMayor { get; set; }
        public long Identificador { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
