//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4AppFuncional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Bodegas = new HashSet<Bodegas>();
        }       

        public int IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
    
        public virtual ICollection<Bodegas> Bodegas { get; set; }
    }
}
