//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4AppFuncional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Cotizaciones = new HashSet<Cotizaciones>();
        }
    
        public int NoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string GiroEmpresarial { get; set; }
        public string PrioridadVenta { get; set; }
    
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
    }
}
