//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc4AppFuncional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public int Id { get; set; }
        public int NoCliente { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public string Gironegocio { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
